### ISSUE TITLE
Don't use Fanout Exchange for retry strategy

### ISSUE THREAD

**Issue by andrelugomes** [Tradeshift/spring-rabbitmq-tuning#11]
Hi @juliofalbo great lib, starting using and contributing.

I believe that we can't use fanout because, all queues are bindings in the same exchange, and using routing key to doing the Retry and DLQ strategy.

What do you think?

**Comment by andrelugomes** [comment]
```
else if ("fanout".equals(properties.getExchangeType())) {
            exchange = new FanoutExchange(properties.getExchange(), true, false);
        }
```

**Comment by andrelugomes** [comment]
Or only use Topic and Direct exchanges for Retries...

**Comment by juliofalbo** [comment]
Yes we can do that. So we need to create an exception that will be thrown if the user tries to use the `@EnableRabbitRetryAndDlq` annotation and send a queue that is bound to a Fanout.

**Comment by andrelugomes** [comment]
I think is not a good idea throwing an Exception in Runtime. I believe just ignoring sound good for now.
Maybe a little warning on the logs. 

What you think?

**Comment by juliofalbo** [comment]
#16
