### ISSUE TITLE
autoCreate doesn't work when there are multiples events in the same Host, Port and Virtual Host.

### ISSUE THREAD

**Issue by wesleyegberto** [Tradeshift/spring-rabbitmq-tuning#21]
The autoCreate doesn't work when there are multiples events in the same Host, Port and Virtual Host.

After same investigation, I noted that the `TunedRabbitAutoConfiguration.createRabbitMQArch(TunedRabbitProperties)` checks if there is an arch created for the Host and Port or for the Virtual Host.
When already exists one it only returns it.

I think if it already have the arch it should keep going and creating the binding for the queue.

I'm trying to modify it so it could create only the binding.

**Comment by juliofalbo** [comment]
@wesleyegberto , amazing job!

This is a bug in our autocreation and your analysis is correct! Thanks for the PR, I'm really looking forward to merge it!
If you need any help, please, send me a message!
