### ISSUE TITLE
Connection to a RabbitMQ cluster

### ISSUE THREAD

**Issue by rrnovaesjr** [Tradeshift/spring-rabbitmq-tuning#35]
Hi everyone,

I was investigating the properties on https://github.com/Tradeshift/spring-rabbitmq-tuning/wiki/Properties-Documentation and did not find anything that was supposed to be similar to Spring's `spring.rabbitmq.addresses` property.

Is this library compatible with Spring's properties as well? Is there any way to connect to a cluster?

**Comment by wesleyegberto** [comment]
Hi, I'm trying some changes to support that.

This lib is using Spring Amqp but not its properties (like `spring.rabbitmq.addresses`).

Currently it cannot connect to a cluster because of how it is creating a `ConnectionFactory`, by only calling:

```java
factory.setHost(property.getHost());
factory.setPort(property.getPort());
```

I think the lib will need to change [this](https://github.com/Tradeshift/spring-rabbitmq-tuning/blob/master/src/main/java/com/tradeshift/amqp/rabbit/components/RabbitComponentsFactory.java#L63-L68) a bit so Spring class could use the method `ConnectionFactory.createConnection(addressesList)` (`CachingConnectionFactory` will call that method when it has the property `addresses` filled).

Maybe this new properties could help define which way to go.

```
spring.rabbitmq.custom.<YOUR_EVENT>.clusterMode=true
spring.rabbitmq.custom.<YOUR_EVENT>.hosts=localhost:5672,localhost:6672,localhost:7672
````

```java
if (property.isClusterMode()) {
        CachingConnectionFactory connFact = new CachingConnectionFactory(factory);
        connFact.setAddresses(property.getHosts());
        return cachingConnectionFactory;
}
factory.setHost(property.getHost());
factory.setPort(property.getPort());
return new CachingConnectionFactory(factory);
```

@juliofalbo , what do you think?

**Comment by juliofalbo** [comment]
First I would like @rrnovaesjr for the issue!

Now, talking about the response, I fully agree with you @wesleyegberto !

It looks a little change that will give to us a great feature.

Will you drive this issue @wesleyegberto ?

Would be amazing!!!

**Comment by wesleyegberto** [comment]
Sure.

[Here](https://github.com/wesleyegberto/spring-rabbitmq-tuning/commit/d1825e3189740989fe4c06aa6174b32f4369c0eb) is the commit to enable connection to cluster that I've been using.

I need some review in this points:

* [Set of hosts and ports](https://github.com/wesleyegberto/spring-rabbitmq-tuning/commit/d1825e3189740989fe4c06aa6174b32f4369c0eb#diff-c9b0dcc61f17ee165b9dbc37f351ad28R205): I've changed the way it [creates the key](https://github.com/wesleyegberto/spring-rabbitmq-tuning/commit/d1825e3189740989fe4c06aa6174b32f4369c0eb#diff-c9b0dcc61f17ee165b9dbc37f351ad28R278-R285) to use in the Set to allow me to identify if a connection to a cluster was defined (using property `hosts`);
* [Beans name](https://github.com/wesleyegberto/spring-rabbitmq-tuning/commit/d1825e3189740989fe4c06aa6174b32f4369c0eb#diff-8501afc27100493458532f9dac6715d9R145-R152): I've changed the way it define the bean name used to [store](https://github.com/wesleyegberto/spring-rabbitmq-tuning/commit/d1825e3189740989fe4c06aa6174b32f4369c0eb#diff-c9b0dcc61f17ee165b9dbc37f351ad28R175) the created bean, this way we can [get the bean name](https://github.com/wesleyegberto/spring-rabbitmq-tuning/commit/d1825e3189740989fe4c06aa6174b32f4369c0eb#diff-c9b0dcc61f17ee165b9dbc37f351ad28R229) by passing only the properties.

If this [naming strategy](https://github.com/wesleyegberto/spring-rabbitmq-tuning/commit/d1825e3189740989fe4c06aa6174b32f4369c0eb#diff-8501afc27100493458532f9dac6715d9R148) is ok I'm planning to change any ref to the methods from `RabbitBeanNameResolver` that receive host and port to force the use of properties object.

After that I will write the tests.

**Comment by wesleyegberto** [comment]
As the PR #38 was merged I think this can be closed.

**Comment by rrnovaesjr** [comment]
Hi everyone! Thanks a lot for all the help. Appreciate it!
